apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aplicacion-ms
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ignacioeuy/argoCD.git
    targetRevision: HEAD
    path: dev
  destination: 
    server: https://kubernetes.default.svc
    namespace: app1

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true