apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
  namespace: argocd
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - image: 538758558904.dkr.ecr.us-east-1.amazonaws.com/micro-servicios:latest
        name: payments
        ports:
        - containerPort: 80
